### ISSUE TITLE
【ツアー詳細】複数ガイドの情報を更新することができない場合がある

### ISSUE THREAD

**Issue by TomSuzuki** [e-harp-intern/R4FY#553]
ログを見た感じ、デッドロックっぽいことが発生しているみたいです。

<details>

<summary>ログ</summary>

```
  Admin Load (0.1ms)  SELECT "admins".* FROM "admins" WHERE "admins"."id" = ? LIMIT ?  [["id", 6], ["LIMIT", 1]]
  ↳ app/controllers/application_controller.rb:32:in `require_login'
Processing by Api::V1::ToursController#update as JSON
  GuideSchedule Load (0.2ms)  SELECT "guide_schedules".* FROM "guide_schedules" WHERE "guide_schedules"."tour_id" = ? AND "guide_schedules"."guide_id" = ? LIMIT ?  [["tour_id", 14], ["guide_id", 12], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/tours_controller.rb:98:in `update'
  Parameters: {"possible"=>true, "tour_id"=>"14", "guide_id"=>"13", "tour"=>{}}
   (0.1ms)  SELECT sqlite_version(*)
  ↳ app/controllers/application_controller.rb:32:in `require_login'
  TRANSACTION (0.1ms)  begin transaction
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  Admin Load (0.2ms)  SELECT "admins".* FROM "admins" WHERE "admins"."id" = ? LIMIT ?  [["id", 6], ["LIMIT", 1]]
  ↳ app/controllers/application_controller.rb:32:in `require_login'
  Guide Load (0.2ms)  SELECT "guides".* FROM "guides" WHERE "guides"."id" = ? LIMIT ?  [["id", 12], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  GuideSchedule Load (0.2ms)  SELECT "guide_schedules".* FROM "guide_schedules" WHERE "guide_schedules"."tour_id" = ? AND "guide_schedules"."guide_id" = ? LIMIT ?  [["tour_id", 14], ["guide_id", 13], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/tours_controller.rb:98:in `update'
  TRANSACTION (0.1ms)  begin transaction
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  Guide Load (0.1ms)  SELECT "guides".* FROM "guides" WHERE "guides"."id" = ? LIMIT ?  [["id", 13], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  Tour Load (0.2ms)  SELECT "tours".* FROM "tours" WHERE "tours"."id" = ? LIMIT ?  [["id", 14], ["LIMIT", 1]]
  Tour Load (0.2ms)  SELECT "tours".* FROM "tours" WHERE "tours"."id" = ? LIMIT ?  [["id", 14], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  GuideSchedule Update (0.2ms)  UPDATE "guide_schedules" SET "answered" = ?, "possible" = ?, "updated_at" = ? WHERE "guide_schedules"."id" = ?  [["answered", 1], ["possible", 1], ["updated_at", "2022-09-26 03:50:18.824721"], ["id", 22]]
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  GuideSchedule Update (5379.4ms)  UPDATE "guide_schedules" SET "answered" = ?, "possible" = ?, "updated_at" = ? WHERE "guide_schedules"."id" = ?  [["answered", 1], ["possible", 1], ["updated_at", "2022-09-26 03:50:18.826457"], ["id", 23]]
  TRANSACTION (5009.5ms)  commit transaction
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  TRANSACTION (0.1ms)  rollback transaction
  TRANSACTION (0.2ms)  rollback transaction
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
Rendering 500 with exception: SQLite3::BusyException: database is locked
Rendering 500 with exception: SQLite3::BusyException: database is locked
Completed 200 OK in 5412ms (Views: 0.3ms | ActiveRecord: 5380.7ms | Allocations: 10447)
```
</details>

**Comment by TomSuzuki** [comment]
<details>
  <summary>ログ２</summary>

```
Started PATCH "/api/v1/tours/23/guides/17/schedules" for 61.198.28.222 at 2022-10-05 00:35:33 +0000
Processing by Api::V1::ToursController#update as JSON
  Parameters: {"possible"=>true, "tour_id"=>"23", "guide_id"=>"17", "tour"=>{}}
  Admin Load (0.1ms)  SELECT "admins".* FROM "admins" WHERE "admins"."id" = ? LIMIT ?  [["id", 6], ["LIMIT", 1]]
  ↳ app/controllers/application_controller.rb:32:in `require_login'
  GuideSchedule Load (0.2ms)  SELECT "guide_schedules".* FROM "guide_schedules" WHERE "guide_schedules"."tour_id" = ? AND "guide_schedules"."guide_id" = ? LIMIT ?  [["tour_id", 23], ["guide_id", 17], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/tours_controller.rb:98:in `update'
  TRANSACTION (0.1ms)  begin transaction
Started PATCH "/api/v1/tours/23/guides/18/schedules" for 61.198.28.222 at 2022-10-05 00:35:33 +0000
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  Guide Load (0.1ms)  SELECT "guides".* FROM "guides" WHERE "guides"."id" = ? LIMIT ?  [["id", 17], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  Tour Load (0.1ms)  SELECT "tours".* FROM "tours" WHERE "tours"."id" = ? LIMIT ?  [["id", 23], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  GuideSchedule Update (0.5ms)  UPDATE "guide_schedules" SET "answered" = ?, "possible" = ?, "updated_at" = ? WHERE "guide_schedules"."id" = ?  [["answered", 1], ["possible", 1], ["updated_at", "2022-10-05 00:35:33.560898"], ["id", 71]]
Processing by Api::V1::ToursController#update as JSON
Started PATCH "/api/v1/tours/23/guides/19/schedules" for 61.198.28.222 at 2022-10-05 00:35:33 +0000
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  Parameters: {"possible"=>true, "tour_id"=>"23", "guide_id"=>"18", "tour"=>{}}
  TRANSACTION (2.4ms)  commit transaction
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
Completed 200 OK in 40ms (Views: 0.3ms | ActiveRecord: 3.5ms | Allocations: 9694)


Started PATCH "/api/v1/tours/23/guides/20/schedules" for 61.198.28.222 at 2022-10-05 00:35:33 +0000
Processing by Api::V1::ToursController#update as JSON
  Admin Load (0.1ms)  SELECT "admins".* FROM "admins" WHERE "admins"."id" = ? LIMIT ?  [["id", 6], ["LIMIT", 1]]
  Parameters: {"possible"=>true, "tour_id"=>"23", "guide_id"=>"19", "tour"=>{}}
  ↳ app/controllers/application_controller.rb:32:in `require_login'
  Admin Load (0.2ms)  SELECT "admins".* FROM "admins" WHERE "admins"."id" = ? LIMIT ?  [["id", 6], ["LIMIT", 1]]
  GuideSchedule Load (0.3ms)  SELECT "guide_schedules".* FROM "guide_schedules" WHERE "guide_schedules"."tour_id" = ? AND "guide_schedules"."guide_id" = ? LIMIT ?  [["tour_id", 23], ["guide_id", 18], ["LIMIT", 1]]
  ↳ app/controllers/application_controller.rb:32:in `require_login'
  ↳ app/controllers/api/v1/tours_controller.rb:98:in `update'
Started PATCH "/api/v1/tours/23/guides/21/schedules" for 61.198.28.222 at 2022-10-05 00:35:33 +0000
  GuideSchedule Load (0.2ms)  SELECT "guide_schedules".* FROM "guide_schedules" WHERE "guide_schedules"."tour_id" = ? AND "guide_schedules"."guide_id" = ? LIMIT ?  [["tour_id", 23], ["guide_id", 19], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/tours_controller.rb:98:in `update'
  TRANSACTION (0.1ms)  begin transaction
  TRANSACTION (0.1ms)  begin transaction
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
Processing by Api::V1::ToursController#update as JSON
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  Guide Load (0.2ms)  SELECT "guides".* FROM "guides" WHERE "guides"."id" = ? LIMIT ?  [["id", 18], ["LIMIT", 1]]
  Parameters: {"possible"=>true, "tour_id"=>"23", "guide_id"=>"20", "tour"=>{}}
  Guide Load (0.1ms)  SELECT "guides".* FROM "guides" WHERE "guides"."id" = ? LIMIT ?  [["id", 19], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  Tour Load (0.2ms)  SELECT "tours".* FROM "tours" WHERE "tours"."id" = ? LIMIT ?  [["id", 23], ["LIMIT", 1]]
   (0.1ms)  SELECT sqlite_version(*)
Started PATCH "/api/v1/tours/23/guides/22/schedules" for 61.198.28.222 at 2022-10-05 00:35:33 +0000
  Tour Load (0.6ms)  SELECT "tours".* FROM "tours" WHERE "tours"."id" = ? LIMIT ?  [["id", 23], ["LIMIT", 1]]
Processing by Api::V1::ToursController#update as JSON
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  ↳ app/controllers/application_controller.rb:32:in `require_login'
  Parameters: {"possible"=>true, "tour_id"=>"23", "guide_id"=>"21", "tour"=>{}}
  GuideSchedule Update (0.4ms)  UPDATE "guide_schedules" SET "answered" = ?, "possible" = ?, "updated_at" = ? WHERE "guide_schedules"."id" = ?  [["answered", 1], ["possible", 1], ["updated_at", "2022-10-05 00:35:33.633384"], ["id", 72]]
  Admin Load (0.2ms)  SELECT "admins".* FROM "admins" WHERE "admins"."id" = ? LIMIT ?  [["id", 6], ["LIMIT", 1]]
   (0.1ms)  SELECT sqlite_version(*)
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  GuideSchedule Update (0.4ms)  UPDATE "guide_schedules" SET "answered" = ?, "possible" = ?, "updated_at" = ? WHERE "guide_schedules"."id" = ?  [["answered", 1], ["possible", 1], ["updated_at", "2022-10-05 00:35:33.641793"], ["id", 73]]
  ↳ app/controllers/application_controller.rb:32:in `require_login'
  ↳ app/controllers/application_controller.rb:32:in `require_login'
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
Processing by Api::V1::ToursController#update as JSON
  TRANSACTION (5007.1ms)  commit transaction
  Admin Load (5007.7ms)  SELECT "admins".* FROM "admins" WHERE "admins"."id" = ? LIMIT ?  [["id", 6], ["LIMIT", 1]]
  GuideSchedule Load (5007.9ms)  SELECT "guide_schedules".* FROM "guide_schedules" WHERE "guide_schedules"."tour_id" = ? AND "guide_schedules"."guide_id" = ? LIMIT ?  [["tour_id", 23], ["guide_id", 20], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/tours_controller.rb:98:in `update'
  Parameters: {"possible"=>true, "tour_id"=>"23", "guide_id"=>"22", "tour"=>{}}
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  ↳ app/controllers/application_controller.rb:32:in `require_login'
  TRANSACTION (0.1ms)  rollback transaction
Rendering 500 with exception: SQLite3::BusyException: database is locked
Completed 200 OK in 25060ms (Views: 0.3ms | ActiveRecord: 5008.2ms | Allocations: 6790)


  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
Rendering 500 with exception: SQLite3::BusyException: database is locked
Rendering 500 with exception: SQLite3::BusyException: database is locked
Completed 200 OK in 25110ms (Views: 0.1ms | ActiveRecord: 1.2ms | Allocations: 19187)


Completed 200 OK in 25084ms (Views: 0.1ms | ActiveRecord: 5008.8ms | Allocations: 12230)


  TRANSACTION (0.4ms)  rollback transaction
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
Rendering 500 with exception: SQLite3::BusyException: database is locked
Completed 200 OK in 30142ms (Views: 0.2ms | ActiveRecord: 5009.2ms | Allocations: 25088)


Started PATCH "/api/v1/tours/23/guides/23/schedules" for 61.198.28.222 at 2022-10-05 00:36:03 +0000
   (10035.5ms)  SELECT sqlite_version(*)
  ↳ app/controllers/application_controller.rb:32:in `require_login'
  Admin Load (0.5ms)  SELECT "admins".* FROM "admins" WHERE "admins"."id" = ? LIMIT ?  [["id", 6], ["LIMIT", 1]]
Started PATCH "/api/v1/tours/23/guides/24/schedules" for 61.198.28.222 at 2022-10-05 00:36:03 +0000
  ↳ app/controllers/application_controller.rb:32:in `require_login'
  GuideSchedule Load (0.2ms)  SELECT "guide_schedules".* FROM "guide_schedules" WHERE "guide_schedules"."tour_id" = ? AND "guide_schedules"."guide_id" = ? LIMIT ?  [["tour_id", 23], ["guide_id", 22], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/tours_controller.rb:98:in `update'
  TRANSACTION (0.1ms)  begin transaction
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
Processing by Api::V1::ToursController#update as JSON
Processing by Api::V1::ToursController#update as JSON
  Guide Load (0.2ms)  SELECT "guides".* FROM "guides" WHERE "guides"."id" = ? LIMIT ?  [["id", 22], ["LIMIT", 1]]
  Parameters: {"possible"=>true, "tour_id"=>"23", "guide_id"=>"24", "tour"=>{}}
  Parameters: {"possible"=>true, "tour_id"=>"23", "guide_id"=>"23", "tour"=>{}}
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  Admin Load (0.2ms)  SELECT "admins".* FROM "admins" WHERE "admins"."id" = ? LIMIT ?  [["id", 6], ["LIMIT", 1]]
  Admin Load (0.3ms)  SELECT "admins".* FROM "admins" WHERE "admins"."id" = ? LIMIT ?  [["id", 6], ["LIMIT", 1]]
  Tour Load (0.2ms)  SELECT "tours".* FROM "tours" WHERE "tours"."id" = ? LIMIT ?  [["id", 23], ["LIMIT", 1]]
  ↳ app/controllers/application_controller.rb:32:in `require_login'
  ↳ app/controllers/application_controller.rb:32:in `require_login'
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  GuideSchedule Load (0.1ms)  SELECT "guide_schedules".* FROM "guide_schedules" WHERE "guide_schedules"."tour_id" = ? AND "guide_schedules"."guide_id" = ? LIMIT ?  [["tour_id", 23], ["guide_id", 24], ["LIMIT", 1]]
  GuideSchedule Load (0.1ms)  SELECT "guide_schedules".* FROM "guide_schedules" WHERE "guide_schedules"."tour_id" = ? AND "guide_schedules"."guide_id" = ? LIMIT ?  [["tour_id", 23], ["guide_id", 23], ["LIMIT", 1]]
  GuideSchedule Update (0.3ms)  UPDATE "guide_schedules" SET "answered" = ?, "possible" = ?, "updated_at" = ? WHERE "guide_schedules"."id" = ?  [["answered", 1], ["possible", 1], ["updated_at", "2022-10-05 00:36:03.751917"], ["id", 76]]
  ↳ app/controllers/api/v1/tours_controller.rb:98:in `update'
  ↳ app/controllers/api/v1/tours_controller.rb:98:in `update'
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  TRANSACTION (0.1ms)  begin transaction
  TRANSACTION (0.0ms)  begin transaction
  TRANSACTION (5.0ms)  commit transaction
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  Guide Load (0.2ms)  SELECT "guides".* FROM "guides" WHERE "guides"."id" = ? LIMIT ?  [["id", 24], ["LIMIT", 1]]
  Guide Load (0.2ms)  SELECT "guides".* FROM "guides" WHERE "guides"."id" = ? LIMIT ?  [["id", 23], ["LIMIT", 1]]
Completed 200 OK in 15090ms (Views: 0.5ms | ActiveRecord: 15048.6ms | Allocations: 17399)


  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  Tour Load (0.1ms)  SELECT "tours".* FROM "tours" WHERE "tours"."id" = ? LIMIT ?  [["id", 23], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  Tour Load (0.1ms)  SELECT "tours".* FROM "tours" WHERE "tours"."id" = ? LIMIT ?  [["id", 23], ["LIMIT", 1]]
  GuideSchedule Update (0.3ms)  UPDATE "guide_schedules" SET "answered" = ?, "possible" = ?, "updated_at" = ? WHERE "guide_schedules"."id" = ?  [["answered", 1], ["possible", 1], ["updated_at", "2022-10-05 00:36:03.777250"], ["id", 78]]
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  GuideSchedule Update (0.3ms)  UPDATE "guide_schedules" SET "answered" = ?, "possible" = ?, "updated_at" = ? WHERE "guide_schedules"."id" = ?  [["answered", 1], ["possible", 1], ["updated_at", "2022-10-05 00:36:03.780820"], ["id", 77]]
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  TRANSACTION (0.1ms)  rollback transaction
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  TRANSACTION (5006.8ms)  commit transaction
Rendering 500 with exception: SQLite3::BusyException: database is locked
Completed 200 OK in 5052ms (Views: 0.4ms | ActiveRecord: 1.2ms | Allocations: 12860)


  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
  TRANSACTION (0.2ms)  rollback transaction
  ↳ app/controllers/api/v1/tours_controller.rb:102:in `update'
Rendering 500 with exception: SQLite3::BusyException: database is locked
Completed 200 OK in 5058ms (Views: 0.4ms | ActiveRecord: 5007.9ms | Allocations: 14434)


Started GET "/api/v1/tours/23" for 61.198.28.222 at 2022-10-05 00:36:08 +0000
Processing by Api::V1::TourController#index as JSON
  Parameters: {"id"=>"23", "tour"=>{}}
  Admin Load (0.1ms)  SELECT "admins".* FROM "admins" WHERE "admins"."id" = ? LIMIT ?  [["id", 6], ["LIMIT", 1]]
  ↳ app/controllers/application_controller.rb:32:in `require_login'
  Tour Load (0.1ms)  SELECT "tours".* FROM "tours" WHERE "tours"."id" = ? LIMIT ?  [["id", 23], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/tour_controller.rb:8:in `index'
  GuideSchedule Load (0.2ms)  SELECT "guide_schedules".* FROM "guide_schedules" WHERE "guide_schedules"."tour_id" = ?  [["tour_id", 23]]
  ↳ app/controllers/api/v1/tour_controller.rb:21:in `index'
  Guide Load (0.5ms)  SELECT "guides".* FROM "guides" WHERE "guides"."id" IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)  [["id", 11], ["id", 12], ["id", 13], ["id", 14], ["id", 15], ["id", 17], ["id", 18], ["id", 19], ["id", 20], ["id", 21], ["id", 22], ["id", 23], ["id", 24]]
  ↳ app/controllers/api/v1/tour_controller.rb:21:in `index'
  TourGuide Load (0.2ms)  SELECT "tour_guides".* FROM "tour_guides" WHERE "tour_guides"."tour_id" = ?  [["tour_id", 23]]
  ↳ app/controllers/api/v1/tour_controller.rb:22:in `index'
Completed 200 OK in 17ms (Views: 1.2ms | ActiveRecord: 1.2ms | Allocations: 8860)
```

</details>

**Comment by TomSuzuki** [comment]
現状： 楽観的ロック ...2つ目の処理がエラーになる

## 参考サイト
- [Railsの楽観的ロックと悲観的ロックの違い｜Railsのロック制御を完全理解する](https://zenn.dev/shuhei_takada/books/3ff66325f45adc/viewer/2bf43c)
- [Rails 7: with_lockでもtransactionのロック戦略引数を指定可能になった（翻訳）｜TechRacho by BPS株式会社](https://techracho.bpsinc.jp/hachi8833/2022_04_01/116801)

**Comment by TomSuzuki** [comment]
単一での更新ではなく、一括で更新するAPIを作成する必要がある。
